package nz.ac.canterbury.seng302.homehelper.unit.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;
import nz.ac.canterbury.seng302.homehelper.dto.UserDTO;
import nz.ac.canterbury.seng302.homehelper.entity.User;
import nz.ac.canterbury.seng302.homehelper.service.UserService;
import nz.ac.canterbury.seng302.homehelper.utils.UserDataValidator;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class UserDataValidatorTest {

    private final User john = new User("john@example.com", "John", "Doe", "password");
    UserDTO testData;
    HashMap<String, String> errors;
    @Mock
    private UserService userService;

    // Method generated by ChatGPT
    private static Stream<Arguments> validFirstNames() {
        return Stream.of(
                Arguments.of("José"),
                Arguments.of("Zoë"),
                Arguments.of("François"),
                Arguments.of("Björk"),
                Arguments.of("Łukasz"),
                Arguments.of("Élise"),
                Arguments.of("Håkon"),
                Arguments.of("André"),
                Arguments.of("Søren"),
                Arguments.of("Álvaro"),
                Arguments.of("İsmail"),
                Arguments.of("Özge"),
                Arguments.of("Šimon"),
                Arguments.of("Tāne"),
                Arguments.of("أحمد"),
                Arguments.of("李")
        );
    }

    // Generated by ChatGPT
    private static Stream<Arguments> validLastNames() {
        return Stream.of(
                Arguments.of("García"),
                Arguments.of("O'Neill"),
                Arguments.of("Dvořák"),
                Arguments.of("Müller"),
                Arguments.of("Grøn"),
                Arguments.of("Łukowski"),
                Arguments.of("Núñez"),
                Arguments.of("Håkansson"),
                Arguments.of("Jónsdóttir"),
                Arguments.of("Červený"),
                Arguments.of("Kovačić"),
                Arguments.of("Öztürk"),
                Arguments.of("Tāmati"),
                Arguments.of("Šarić"),
                Arguments.of("عبدالله"),
                Arguments.of("王")
        );
    }

    private static Stream<Arguments> validPasswords() {
        return Stream.of(
                Arguments.of("P4$$word"),
                Arguments.of("GoodPassword123!"),
                Arguments.of("Pass12!*"),
                Arguments.of("@!#$%^&*()1Aa")
        );
    }

    // Generated by ChatGPT
    private static Stream<Arguments> validEmails() {
        return Stream.of(
                Arguments.of("test@example.com"),
                Arguments.of("user.name@domain.co"),
                Arguments.of("first.last@sub.domain.com"),
                Arguments.of("username@domain.org"),
                Arguments.of("simple@domain.com"),
                Arguments.of("a".repeat(244) + "@domain.com")
        );
    }

    // Generated by ChatGPT
    private static Stream<Arguments> invalidEmails() {
        return Stream.of(
                Arguments.of("plainaddress"),
                Arguments.of("missing@domain"),
                Arguments.of("user@.com"),
                Arguments.of("user@domain..com"),
                Arguments.of("user@domain,com"),
                Arguments.of("user@domain@com"),
                Arguments.of("@nodomain.com"),
                Arguments.of("user@domain#com"),
                Arguments.of("user@domain.com "),
                Arguments.of("user@.com."),
                Arguments.of("double..dot@domain.co"),
                Arguments.of("dot.before.@domain.co")

        );
    }

    private static Stream<Arguments> tooLongEmails() {
        return Stream.of(
                Arguments.of("a".repeat(256)),
                Arguments.of("a".repeat(1000)),
                Arguments.of("a".repeat(256) + "@example.com")
        );
    }

    private static Stream<Arguments> tooLongPasswords() {
        return Stream.of(
                Arguments.of("a".repeat(256)),
                Arguments.of("a".repeat(1000)),
                Arguments.of("a".repeat(256) + "P4$$word"),
                Arguments.of("a".repeat(256) + "Pa$$word"),
                Arguments.of("a".repeat(256) + "P4ssword"),
                Arguments.of("a".repeat(256) + "p4$$word")
        );
    }

    // Generated by ChatGPT
    private static Stream<Arguments> validPasswordLengths() {
        return Stream.of(
                Arguments.of("😀".repeat(247) + "P4$$word"),
                Arguments.of("😃".repeat(247) + "P4$$word"),
                Arguments.of("😄".repeat(247) + "P4$$word"),
                Arguments.of("😁".repeat(247) + "P4$$word"),
                Arguments.of("😆".repeat(247) + "P4$$word"),
                Arguments.of("😅".repeat(247) + "P4$$word"),
                Arguments.of("😂".repeat(247) + "P4$$word"),
                Arguments.of("🤣".repeat(247) + "P4$$word"),
                Arguments.of("😊".repeat(247) + "P4$$word"),
                Arguments.of("😇".repeat(247) + "P4$$word"),
                Arguments.of("🙂".repeat(247) + "P4$$word"),
                Arguments.of("🙃".repeat(247) + "P4$$word"),
                Arguments.of("😉".repeat(247) + "P4$$word"),
                Arguments.of("😌".repeat(247) + "P4$$word"),
                Arguments.of("😍".repeat(247) + "P4$$word"),
                Arguments.of("🥰".repeat(247) + "P4$$word"),
                Arguments.of("😘".repeat(247) + "P4$$word"),
                Arguments.of("😗".repeat(247) + "P4$$word"),
                Arguments.of("😙".repeat(247) + "P4$$word"),
                Arguments.of("😚".repeat(247) + "P4$$word"),
                Arguments.of("😋".repeat(247) + "P4$$word"),
                Arguments.of("😛".repeat(247) + "P4$$word"),
                Arguments.of("😝".repeat(247) + "P4$$word"),
                Arguments.of("😜".repeat(247) + "P4$$word"),
                Arguments.of("🤪".repeat(247) + "P4$$word"),
                Arguments.of("🤨".repeat(247) + "P4$$word"),
                Arguments.of("🧐".repeat(247) + "P4$$word"),
                Arguments.of("🤓".repeat(247) + "P4$$word"),
                Arguments.of("😎".repeat(247) + "P4$$word"),
                Arguments.of("🥸".repeat(247) + "P4$$word"),
                Arguments.of("🤩".repeat(247) + "P4$$word"),
                Arguments.of("🥳".repeat(247) + "P4$$word"),
                Arguments.of("😏".repeat(247) + "P4$$word"),
                Arguments.of("😒".repeat(247) + "P4$$word"),
                Arguments.of("😞".repeat(247) + "P4$$word"),
                Arguments.of("😔".repeat(247) + "P4$$word"),
                Arguments.of("😟".repeat(247) + "P4$$word"),
                Arguments.of("😕".repeat(247) + "P4$$word"),
                Arguments.of("🙁".repeat(247) + "P4$$word"),
//                Arguments.of("☹️".repeat(247) + "P4$$word"),
                Arguments.of("😣".repeat(247) + "P4$$word"),
                Arguments.of("😖".repeat(247) + "P4$$word"),
                Arguments.of("😫".repeat(247) + "P4$$word"),
                Arguments.of("😩".repeat(247) + "P4$$word"),
                Arguments.of("🥺".repeat(247) + "P4$$word"),
                Arguments.of("😢".repeat(247) + "P4$$word"),
                Arguments.of("😭".repeat(247) + "P4$$word"),
                Arguments.of("😤".repeat(247) + "P4$$word"),
                Arguments.of("😠".repeat(247) + "P4$$word"),
                Arguments.of("😡".repeat(247) + "P4$$word"),
                Arguments.of("🤬".repeat(247) + "P4$$word"),
                Arguments.of("🤯".repeat(247) + "P4$$word"),
                Arguments.of("😳".repeat(247) + "P4$$word"),
                Arguments.of("🥵".repeat(247) + "P4$$word"),
                Arguments.of("🥶".repeat(247) + "P4$$word"),
                Arguments.of("😱".repeat(247) + "P4$$word"),
                Arguments.of("😨".repeat(247) + "P4$$word"),
                Arguments.of("😰".repeat(247) + "P4$$word"),
                Arguments.of("😥".repeat(247) + "P4$$word"),
                Arguments.of("😓".repeat(247) + "P4$$word"),
                Arguments.of("🤗".repeat(247) + "P4$$word"),
                Arguments.of("🤔".repeat(247) + "P4$$word"),
                Arguments.of("🤭".repeat(247) + "P4$$word"),
                Arguments.of("🤫".repeat(247) + "P4$$word"),
                Arguments.of("🤥".repeat(247) + "P4$$word"),
                Arguments.of("😶".repeat(247) + "P4$$word"),
                Arguments.of("😐".repeat(247) + "P4$$word"),
                Arguments.of("😑".repeat(247) + "P4$$word"),
                Arguments.of("😬".repeat(247) + "P4$$word"),
                Arguments.of("🙄".repeat(247) + "P4$$word"),
                Arguments.of("😯".repeat(247) + "P4$$word"),
                Arguments.of("😦".repeat(247) + "P4$$word"),
                Arguments.of("😧".repeat(247) + "P4$$word"),
                Arguments.of("😮".repeat(247) + "P4$$word"),
                Arguments.of("😲".repeat(247) + "P4$$word"),
                Arguments.of("🥱".repeat(247) + "P4$$word"),
                Arguments.of("😴".repeat(247) + "P4$$word"),
                Arguments.of("🤤".repeat(247) + "P4$$word"),
                Arguments.of("😪".repeat(247) + "P4$$word"),
                Arguments.of("😵".repeat(247) + "P4$$word"),
                Arguments.of("🤐".repeat(247) + "P4$$word"),
                Arguments.of("🥴".repeat(247) + "P4$$word"),
                Arguments.of("🤢".repeat(247) + "P4$$word"),
                Arguments.of("🤮".repeat(247) + "P4$$word"),
                Arguments.of("🤧".repeat(247) + "P4$$word"),
                Arguments.of("😷".repeat(247) + "P4$$word"),
                Arguments.of("🤒".repeat(247) + "P4$$word"),
                Arguments.of("🤕".repeat(247) + "P4$$word"),
                Arguments.of("🤑".repeat(247) + "P4$$word"),
                Arguments.of("🤠".repeat(247) + "P4$$word"),
                Arguments.of("😈".repeat(247) + "P4$$word"),
                Arguments.of("👿".repeat(247) + "P4$$word"),
                Arguments.of("👹".repeat(247) + "P4$$word"),
                Arguments.of("👺".repeat(247) + "P4$$word"),
                Arguments.of("🤡".repeat(247) + "P4$$word"),
                Arguments.of("💩".repeat(247) + "P4$$word"),
                Arguments.of("👻".repeat(247) + "P4$$word"),
                Arguments.of("💀".repeat(247) + "P4$$word"),
//                Arguments.of("☠️".repeat(247) + "P4$$word"),
                Arguments.of("👽".repeat(247) + "P4$$word"),
                Arguments.of("👾".repeat(247) + "P4$$word"),
                Arguments.of("🤖".repeat(247) + "P4$$word"),
                Arguments.of("🎃".repeat(247) + "P4$$word"),
                Arguments.of("😺".repeat(247) + "P4$$word"),
                Arguments.of("😸".repeat(247) + "P4$$word"),
                Arguments.of("😹".repeat(247) + "P4$$word"),
                Arguments.of("😻".repeat(247) + "P4$$word"),
                Arguments.of("😼".repeat(247) + "P4$$word"),
                Arguments.of("😽".repeat(247) + "P4$$word"),
                Arguments.of("🙀".repeat(247) + "P4$$word"),
                Arguments.of("😿".repeat(247) + "P4$$word"),
                Arguments.of("😾".repeat(247) + "P4$$word"),
                Arguments.of("🐶".repeat(247) + "P4$$word"),
                Arguments.of("🐱".repeat(247) + "P4$$word"),
                Arguments.of("🐭".repeat(247) + "P4$$word"),
                Arguments.of("🐹".repeat(247) + "P4$$word"),
                Arguments.of("🐰".repeat(247) + "P4$$word"),
                Arguments.of("🦊".repeat(247) + "P4$$word"),
                Arguments.of("🐻".repeat(247) + "P4$$word"),
                Arguments.of("🐼".repeat(247) + "P4$$word"),
                Arguments.of("🐨".repeat(247) + "P4$$word"),
                Arguments.of("🐯".repeat(247) + "P4$$word"),
                Arguments.of("🦁".repeat(247) + "P4$$word"),
                Arguments.of("🐮".repeat(247) + "P4$$word"),
                Arguments.of("🐷".repeat(247) + "P4$$word"),
                Arguments.of("🐸".repeat(247) + "P4$$word"),
                Arguments.of("🐵".repeat(247) + "P4$$word"),
                Arguments.of("🙈".repeat(247) + "P4$$word"),
                Arguments.of("🙉".repeat(247) + "P4$$word"),
                Arguments.of("🙊".repeat(247) + "P4$$word"),
                Arguments.of("🐒".repeat(247) + "P4$$word"),
                Arguments.of("🐔".repeat(247) + "P4$$word"),
                Arguments.of("🐧".repeat(247) + "P4$$word"),
                Arguments.of("🐦".repeat(247) + "P4$$word"),
                Arguments.of("🐤".repeat(247) + "P4$$word"),
                Arguments.of("🐣".repeat(247) + "P4$$word"),
                Arguments.of("🐥".repeat(247) + "P4$$word"),
                Arguments.of("🦆".repeat(247) + "P4$$word"),
                Arguments.of("🦅".repeat(247) + "P4$$word"),
                Arguments.of("🦉".repeat(247) + "P4$$word"),
                Arguments.of("🦇".repeat(247) + "P4$$word"),
                Arguments.of("🐺".repeat(247) + "P4$$word"),
                Arguments.of("🐗".repeat(247) + "P4$$word"),
                Arguments.of("🐴".repeat(247) + "P4$$word"),
                Arguments.of("🦄".repeat(247) + "P4$$word"),
                Arguments.of("🐝".repeat(247) + "P4$$word"),
                Arguments.of("🪱".repeat(247) + "P4$$word"),
                Arguments.of("🐛".repeat(247) + "P4$$word"),
                Arguments.of("🦋".repeat(247) + "P4$$word"),
                Arguments.of("🐌".repeat(247) + "P4$$word"),
                Arguments.of("🐞".repeat(247) + "P4$$word"),
                Arguments.of("🐜".repeat(247) + "P4$$word"),
                Arguments.of("🪰".repeat(247) + "P4$$word"),
                Arguments.of("🪲".repeat(247) + "P4$$word"),
                Arguments.of("🪳".repeat(247) + "P4$$word"),
//                Arguments.of("🕷️".repeat(247) + "P4$$word"),
//                Arguments.of("🕸️".repeat(247) + "P4$$word"),
                Arguments.of("🦂".repeat(247) + "P4$$word"),
                Arguments.of("🐢".repeat(247) + "P4$$word"),
                Arguments.of("🐍".repeat(247) + "P4$$word"),
                Arguments.of("🦎".repeat(247) + "P4$$word"),
                Arguments.of("🦖".repeat(247) + "P4$$word"),
                Arguments.of("🦕".repeat(247) + "P4$$word"),
                Arguments.of("🐙".repeat(247) + "P4$$word"),
                Arguments.of("🦑".repeat(247) + "P4$$word"),
                Arguments.of("🦐".repeat(247) + "P4$$word"),
                Arguments.of("🦞".repeat(247) + "P4$$word"),
                Arguments.of("🦀".repeat(247) + "P4$$word"),
                Arguments.of("🐡".repeat(247) + "P4$$word"),
                Arguments.of("🐠".repeat(247) + "P4$$word"),
                Arguments.of("🐟".repeat(247) + "P4$$word"),
                Arguments.of("🐬".repeat(247) + "P4$$word"),
                Arguments.of("🐳".repeat(247) + "P4$$word"),
                Arguments.of("🐋".repeat(247) + "P4$$word"),
                Arguments.of("🦈".repeat(247) + "P4$$word"),
                Arguments.of("🐊".repeat(247) + "P4$$word"),
                Arguments.of("🐅".repeat(247) + "P4$$word"),
                Arguments.of("🐆".repeat(247) + "P4$$word"),
                Arguments.of("🦓".repeat(247) + "P4$$word"),
                Arguments.of("🦍".repeat(247) + "P4$$word"),
                Arguments.of("🦧".repeat(247) + "P4$$word"),
                Arguments.of("🦣".repeat(247) + "P4$$word"),
                Arguments.of("🐘".repeat(247) + "P4$$word"),
                Arguments.of("🦛".repeat(247) + "P4$$word"),
                Arguments.of("🦏".repeat(247) + "P4$$word"),
                Arguments.of("🐪".repeat(247) + "P4$$word"),
                Arguments.of("🐫".repeat(247) + "P4$$word"),
                Arguments.of("🦒".repeat(247) + "P4$$word"),
                Arguments.of("🦬".repeat(247) + "P4$$word"),
                Arguments.of("🐃".repeat(247) + "P4$$word"),
                Arguments.of("🐂".repeat(247) + "P4$$word"),
                Arguments.of("🐄".repeat(247) + "P4$$word"),
                Arguments.of("🐎".repeat(247) + "P4$$word"),
                Arguments.of("🐖".repeat(247) + "P4$$word"),
                Arguments.of("🐏".repeat(247) + "P4$$word"),
                Arguments.of("🐑".repeat(247) + "P4$$word"),
                Arguments.of("🦙".repeat(247) + "P4$$word"),
                Arguments.of("🐐".repeat(247) + "P4$$word"),
                Arguments.of("🦌".repeat(247) + "P4$$word"),
                Arguments.of("🐕".repeat(247) + "P4$$word"),
                Arguments.of("🐩".repeat(247) + "P4$$word"),
                Arguments.of("🦮".repeat(247) + "P4$$word"),
//                Arguments.of("🐕‍🦺".repeat(247) + "P4$$word"),
                Arguments.of("🐈".repeat(247) + "P4$$word"),
//                Arguments.of("🐈‍⬛".repeat(247) + "P4$$word"),
                Arguments.of("🪶".repeat(247) + "P4$$word"),
                Arguments.of("🐓".repeat(247) + "P4$$word"),
                Arguments.of("🦃".repeat(247) + "P4$$word"),
                Arguments.of("🦤".repeat(247) + "P4$$word"),
                Arguments.of("🦚".repeat(247) + "P4$$word")
        );
    }

    private static Stream<Arguments> usersAndValidPasswords() {
        return Stream.of(
                Arguments.of(new User("john@example.com", "P4$$word", "John", "Doe"), "P4$$word"),
                Arguments.of(new User("john@example.com", "P4$$word", "John", "Doe"),
                        "P4$$wordJon"),
                Arguments.of(new User("john@example.com", "P4$$word", "John", "Doe"), "P4$$wordDo"),
                Arguments.of(
                        new User("john@example.com", "P4$$word", "John", "Doe"),
                        "P4$$wordjhn@example.com"),
                Arguments.of(new User("john@example.com", "P4$$word", "John", ""), "P4$$word"),
                Arguments.of(new User("john@example.com", "P4$$word", "", "Doe"), "P4$$word"),
                Arguments.of(new User("", "P4$$word", "John", "Doe"), "P4$$word")
        );
    }

    private static Stream<Arguments> usersAndInvalidPasswords() {
        return Stream.of(
                Arguments.of(new User("john@example.com", "P4$$word", "John", "Doe"),
                        "P4$$wordJohn"),
                Arguments.of(new User("john@example.com", "P4$$word", "John", "Doe"),
                        "P4$$wdoeord"),
                Arguments.of(
                        new User("john@example.com", "P4$$word", "John", "Doe"),
                        "P4$$wordJohn@exAmple.cOm"),
                Arguments.of(new User("john@example.com", "P4$$word", "John", ""), "P4$$wordjohn"),
                Arguments.of(new User("john@example.com", "P4$$word", "", "Doe"), "P4$$worddoe"),
                Arguments.of(new User("", "P4$$word", "John", "Doe"), "P4$$wordjohn")
        );
    }

    @BeforeEach
    void init() {
        testData = new UserDTO();
        errors = new HashMap<>();
    }

    @Test
    void validateFirstNameIsEmpty() {
        testData.setFirstName("");
        testData.setLastName("");
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateFirstName(errors, testData.getFirstName());
        Assertions.assertTrue(errors.containsKey("firstName"));

    }

    @Test
    void FirstNameIsTooLong() {
        testData.setFirstName("a".repeat(65));
        testData.setLastName("");
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateFirstName(errors, testData.getFirstName());
        Assertions.assertTrue(errors.containsKey("firstName"));

    }

    @Test
    void FirstNameIsInvalid() {
        testData.setFirstName("!@#$%^&*()");
        testData.setLastName("");
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateFirstName(errors, testData.getFirstName());
        Assertions.assertTrue(errors.containsKey("firstName"));

    }

    @ParameterizedTest
    @MethodSource("validFirstNames")
    void FirstNameIsValid(String firstName) {
        testData.setFirstName(firstName);
        testData.setLastName("");
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateFirstName(errors, testData.getFirstName());
        Assertions.assertTrue(errors.isEmpty());

    }

    @Test
    void LastNameIsEmpty() {
        testData.setFirstName("Jane");
        testData.setLastName("");
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateLastName(errors, testData.getLastName());
        Assertions.assertTrue(errors.isEmpty());
    }

    @Test
    void LastNameIsInvalid() {
        testData.setFirstName("Jane");
        testData.setLastName("!@#$%^&*()");
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateLastName(errors, testData.getLastName());
        Assertions.assertTrue(errors.containsKey("lastName"));
    }

    @ParameterizedTest
    @MethodSource("validLastNames")
    void LastNameIsValid(String lastName) {
        testData.setFirstName("Jane");
        testData.setLastName(lastName);
        testData.setEmail("test@email.com");
        testData.setPassword("TestPassword1!");
        testData.setPasswordConfirm("TestPassword1!");
        UserDataValidator.validateLastName(errors, testData.getLastName());
        Assertions.assertTrue(errors.isEmpty());
    }

    @Test
    void PasswordIsEmpty() {
        testData.setFirstName("Jane");
        testData.setLastName("Doe");
        testData.setEmail("test@email.com");
        testData.setPassword("");
        testData.setPasswordConfirm("");
        UserDataValidator.validatePassword(errors, testData);
        Assertions.assertTrue(errors.containsKey("password"));
    }

    @Test
    void PasswordIsTooShort() {
        testData.setFirstName("Jane");
        testData.setLastName("Doe");
        testData.setEmail("test@email.com");
        testData.setPassword("Weak!");
        testData.setPasswordConfirm("Weak!");
        UserDataValidator.validatePassword(errors, testData);
        Assertions.assertTrue(errors.containsKey("password"));
    }

    @Test
    void PasswordIsTooWeak() {
        testData.setFirstName("Jane");
        testData.setLastName("Doe");
        testData.setEmail("test@email.com");
        testData.setPassword("ReallyLongButWeakPassword");
        testData.setPasswordConfirm("ReallyLongButWeakPassword");
        UserDataValidator.validatePassword(errors, testData);
        Assertions.assertTrue(errors.containsKey("password"));
    }

    @ParameterizedTest
    @MethodSource("validPasswords")
    void PasswordIsValid(String password) {
        testData.setFirstName("Jane");
        testData.setLastName("Doe");
        testData.setEmail("test@email.com");
        testData.setPassword(password);
        testData.setPasswordConfirm(password);
        UserDataValidator.validatePassword(errors, testData);
        Assertions.assertTrue(errors.isEmpty());
    }

    @Test
    void PasswordConfirmDoesNotMatch() {
        testData.setFirstName("Jane");
        testData.setLastName("Doe");
        testData.setEmail("test@email.com");
        testData.setPassword("GoodPassword123!");
        testData.setPasswordConfirm("DoesntMatch!123");
        UserDataValidator.validatePasswordConfirm(errors,
                testData.getPassword(), testData.getPasswordConfirm());
        Assertions.assertTrue(errors.containsKey("confirm"));
    }

    @BeforeEach
    void beforeAll() {
        MockitoAnnotations.openMocks(this);
        when(userService.getUserByEmail(anyString())).thenReturn(Optional.empty());
    }

    @ParameterizedTest
    @MethodSource("validEmails")
    public void validEmail_validateEmailRegex_returnsTrue(String email) {
        assertTrue(UserDataValidator.validateEmailFormat(null, email));
    }

    @ParameterizedTest
    @MethodSource("validEmails")
    public void validEmail_validateEmailRegex_doesntAddError(String email) {
        HashMap<String, String> errors = new HashMap<>();
        UserDataValidator.validateEmailFormat(errors, email);
        assertTrue(errors.isEmpty());
    }

    @ParameterizedTest
    @MethodSource("invalidEmails")
    public void invalidEmail_validateEmailRegex_returnsFalse(String email) {
        assertFalse(UserDataValidator.validateEmailFormat(null, email));
    }

    @ParameterizedTest
    @MethodSource("invalidEmails")
    public void invalidEmail_validateEmailRegex_doesntAddError(String email) {
        HashMap<String, String> errors = new HashMap<>();
        UserDataValidator.validateEmailFormat(errors, email);
        assertTrue(errors.containsKey("email"));
    }

    @ParameterizedTest
    @MethodSource("tooLongEmails")
    public void emailTooLong_validateEmail_addsEmailTooLongErrorMessage(String email) {
        Map<String, String> errors = new HashMap<>();

        UserDataValidator.validateEmail(errors, email, userService, "john@example.com");

        assertTrue(errors.containsKey("email"));
        assertTrue(errors.get("email").contains("Email must be 255 characters long or less"));
    }

    @ParameterizedTest
    @MethodSource("tooLongPasswords")
    public void passwordTooLong_validatePassword_addsPasswordTooLongErrorMessage(String password) {
        Map<String, String> errors = new HashMap<>();

        UserDataValidator.validatePassword(errors, password, john);

        assertTrue(errors.containsKey("password"));
        assertTrue(errors.get("password").contains("Password must be 255 characters long or less"));
    }

    @ParameterizedTest
    @MethodSource("validPasswordLengths")
    public void passwordNotTooLong_validatePassword_doesntAddPasswordTooLongErrorMessage(
            String password) {
        HashMap<String, String> errors = new HashMap<>();

        UserDataValidator.validatePassword(errors, password, john);

        assertFalse(errors.containsKey("password"));
    }

    @ParameterizedTest
    @MethodSource("usersAndValidPasswords")
    public void passwordDoesntContainUserDetails_validatePassword_detailsErrorNotAdded(
            User user, String password) {
        HashMap<String, String> errors = new HashMap<>();

        UserDataValidator.validatePassword(errors, password, user);

        assertTrue(errors.isEmpty());
    }

    @ParameterizedTest
    @MethodSource("usersAndInvalidPasswords")
    public void passwordDoesContainUserDetails_validatePassword_errorAdded(
            User user, String password) {
        HashMap<String, String> errors = new HashMap<>();

        UserDataValidator.validatePassword(errors, password, user);

        assertTrue(errors.containsKey("password"));
        assertEquals(
                "Your password cannot contain any details from your profile.",
                errors.get("password"));
    }
}
