package nz.ac.canterbury.seng302.homehelper.cucumber.step_definitions;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import nz.ac.canterbury.seng302.homehelper.entity.Tag;
import nz.ac.canterbury.seng302.homehelper.service.TagService;
import org.junit.jupiter.api.Assertions;
import org.springframework.beans.factory.annotation.Autowired;

@SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
public class U20_RenovationTagsFeature {

    @Autowired
    TagService tagService;

    ArrayList<Tag> tags = new ArrayList<>();

    private List<Tag> returnedTags;

    @Given("There is a tag {string} in the database")
    public void there_is_a_tag_in_the_database(String string) {
        Tag newTag = new Tag(string);
        tags.add(tagService.save(newTag).get());
    }

    @When("I type {string} in the tag field")
    public void i_type_in_the_tag_field(String string) {
        returnedTags = tagService.getTagsStartingWith(string);
    }

    @When("when I use mix cased words {string}")
    public void when_i_use_mix_cased_words(String string) {
        returnedTags = tagService.getTagsStartingWith(string);
    }

    @Then("there is auto completion showing existing tags that match my input {string}.")
    public void there_is_auto_completion_showing_existing_tags_that_match_my_input(
            String typedString) {

        // Streams here generated by chatGPT
        List<String> expectedMatchingNames = tags.stream()
                .map(Tag::getName)
                .filter(name -> name.toLowerCase().startsWith(typedString.toLowerCase()))
                .collect(Collectors.toList());

        List<String> actualNames = returnedTags.stream()
                .map(Tag::getName)
                .collect(Collectors.toList());

        Assertions.assertTrue(actualNames.containsAll(expectedMatchingNames),
                "Returned tags do not contain all expected tags starting with '" + typedString
                        + "' (case-insensitive)");
    }

}
