package nz.ac.canterbury.seng302.homehelper.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * A resource web configuration class that defines how the user images are to be served to the
 * client. This is required to make sure profile pictures are updated quickly on the client when a
 * user edits them.
 *
 * @author psa94 Penny Sampson
 */
@Configuration
public class ResourceWebConfiguration implements WebMvcConfigurer {

    @Value("${static.resource.folder}")
    private String folder;

    /**
     * JavaDoc generated by ChatGPT Configures resource handlers to serve static files from the
     * "uploads" directory.
     * <p>
     * This method maps requests for "/uploads/**" to the files located in the "uploads" folder on
     * the local file system. For example, a file at "/uploads/myimage.jpg" would be accessible via
     * "http://<server-domain>/uploads/myimage.jpg".
     *
     * @param registry the {@link ResourceHandlerRegistry} used to configure resource handlers.
     */
    @Override
    public void addResourceHandlers(final ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/uploads/**").addResourceLocations("file:" + folder + "/");
    }
}
