spring.datasource.url=jdbc:mariadb://db2.csse.canterbury.ac.nz:3306/seng302-2025-team100-prod?sslmode=trust&characterEncoding=utf8mb4
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
email.resetPassword.baseUrl=https://csse-seng302-team100.canterbury.ac.nz/prod
spring.jpa.hibernate.ddl-auto=validate
scheduler.cron=0 59 23 * * SUN
app.runner.enabled=false
prod.generate=false