spring.datasource.url=jdbc:mariadb://db2.csse.canterbury.ac.nz:3306/seng302-2025-team100-test?sslmode=trust&characterEncoding=utf8mb4
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.schema_drop_handling=drop
app.runner.enabled=true
email.resetPassword.baseUrl=https://csse-seng302-team100.canterbury.ac.nz/test
static.resource.folder=uploads-staging
scheduler.cron=0 59 23 * * SUN
spring.jpa.show-sql=true
prod.generate=false