package nz.ac.canterbury.seng302.homehelper.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import nz.ac.canterbury.seng302.homehelper.entity.Location;
import nz.ac.canterbury.seng302.homehelper.entity.RenovationRecord;
import nz.ac.canterbury.seng302.homehelper.service.RenovationService;
import nz.ac.canterbury.seng302.homehelper.service.UserService;
import nz.ac.canterbury.seng302.homehelper.utils.LocationValidator;
import nz.ac.canterbury.seng302.homehelper.utils.RenovationRecordValidator;
import nz.ac.canterbury.seng302.homehelper.utils.RoomUtilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.server.ResponseStatusException;

@Controller
public class EditRenovationController {

    private final RenovationService renovationService;
    private final RenovationRecordValidator renovationRecordValidator;
    private final UserService userService;
    Logger logger = LoggerFactory.getLogger(MyRenovationsPageController.class);

    @Autowired
    public EditRenovationController(RenovationService renovationService, UserService userService) {
        this.renovationService = renovationService;
        this.renovationRecordValidator = new RenovationRecordValidator();
        this.userService = userService;
    }

    /**
     * Maps the /editRenovation/id URL to editRenovationForm.html
     *
     * @param model representation of the renovation records for use in thymeleaf
     * @return the String representing the name of the edit renovation form html file
     */
    @GetMapping("/editRenovation/{id}")
    public String editRenovation(@PathVariable("id") long id, Model model) {
        logger.info("GET /editRenovation/{}", id);

        RenovationRecord recordToEdit = renovationService.getRenovationRecordById(id);
        if (recordToEdit == null) {
            throw new ResponseStatusException(
                    HttpStatus.NOT_FOUND, "Renovation record with id " + id + " not found");
        }

        Location location = recordToEdit.getRenovationLocation();
        if (location != null) {
            model.addAttribute("location", location);
            model.addAttribute("fullAddress", location.getFullAddress());
        }

        model.addAttribute("renovation", recordToEdit);
        model.addAttribute("descriptionLength", recordToEdit.getDescription().length());

        List<Map<String, Object>> roomSummaries = RoomUtilities.generateSimplifiedRoomSummaries(
                recordToEdit.getRooms());
        model.addAttribute("roomSummaries", roomSummaries);
        model.addAttribute("recordHasUnmodifiableRooms",
                recordToEdit.getUnmodifiableRooms().findAny().isPresent());

        return "editRenovationForm";
    }

    // JavaDoc generated by ChatGPT

    /**
     * Updates an existing renovation record with the specified details.
     * <p>
     * This method handles the submission of a form for editing a renovation record. It updates the
     * renovation record's name, description, and associated rooms based on the provided parameters.
     * If the renovation record is updated successfully, the user is redirected to the
     * "myRenovations" page. If validation fails, the user is returned to the form with an error
     * message.
     *
     * @param id          the ID of the renovation record to be updated
     * @param name        the new name for the renovation record
     * @param description the new description for the renovation record
     * @param roomNames   an optional list of room names associated with the renovation record (can
     *                    be null or empty)
     * @param street      street part of the location
     * @param suburb      suburb part of the location
     * @param city        city part of the location
     * @param postcode    postcode part of the location
     * @param country     country part of the location
     * @param model       the Spring model used to pass attributes to the view (used for error
     *                    messages and form data)
     * @return a String representing the view name (either a redirect to "myRenovations" or a return
     * to the edit form with validation errors)
     */
    @PostMapping("/editRenovation/{id}")
    public String updateRenovation(@PathVariable("id") long id,
            @RequestParam(name = "name") String name,
            @RequestParam(name = "description") String description,
            @RequestParam(name = "roomNames", required = false) List<String> roomNames,
            @RequestParam(name = "roomIds", required = false) List<Long> roomIds,
            @RequestParam(name = "roomName", required = false) String currentRoom,
            @RequestParam(name = "streetAddress", required = false, defaultValue = "") String street,
            @RequestParam(name = "suburb", required = false, defaultValue = "") String suburb,
            @RequestParam(name = "city", required = false, defaultValue = "") String city,
            @RequestParam(name = "postcode", required = false, defaultValue = "") String postcode,
            @RequestParam(name = "country", required = false, defaultValue = "") String country,
            Model model) {
        logger.info("PUT /editRenovation/{}", id);
        roomIds = roomIds == null ? new ArrayList<>() : roomIds;
        RenovationService.ensureIdsNameLengthsEqual(roomIds, roomNames);
        RenovationService.convertNullRoomIds(roomIds);

        // Verify record exists and belongs to logged-in user
        RenovationRecord renovation = renovationService.getRenovationRecordById((id));
        if (renovation == null) {
            throw new ResponseStatusException(
                    HttpStatus.NOT_FOUND, "Renovation record with id " + id + " not found");
        } else if (!userService.userOwnsRecord(renovation)) {
            throw new SecurityException("You do not have permission to edit this record");
        }

        // Location set up and validate
        Location location = new Location(street, suburb, city, postcode, country);
        boolean locationEmpty = LocationValidator.isLocationEmpty(location);

        renovation.setName(name);
        renovation.setDescription(description);

        HashMap<String, String> errors = renovationRecordValidator.validateRenovationRecord(
                renovation);
        renovation.validateUnmodifiableRoomMaintained(errors, roomIds);

        if (!errors.containsKey("unmodifiable")) {
            renovationService.updateRoomsInRenovationRecord(renovation,
                    renovation.reformatRoomNames(roomNames), roomIds);
        }

        renovationService.validateUniqueRenovationRecord(errors,
                renovation.getName(), id);

        if (!locationEmpty) {
            errors.putAll(LocationValidator.validateLocation(location));
        }

        if (errors.isEmpty()) {
            renovationService.save(renovation);
            renovationService.setRenovationLocation(renovation, location);
            return "redirect:/viewRenovation/" + id;

        } else {
            List<Map<String, Object>> roomSummaries = RoomUtilities.generateSimplifiedRoomSummaries(
                    renovation.getRooms());

            model.addAttribute("roomName", currentRoom);
            model.addAttribute("errors", errors);
            model.addAttribute("renovation", renovation);
            model.addAttribute("descriptionLength", renovation.getDescription().length());
            model.addAttribute("roomSummaries", roomSummaries);
            model.addAttribute("recordHasUnmodifiableRooms",
                    renovation.getUnmodifiableRooms().findAny().isPresent());
            if (!locationEmpty) {
                model.addAttribute("fullAddress", location.getFullAddress());
            }
            model.addAttribute("location", location);
            return "editRenovationForm";
        }
    }
}