package nz.ac.canterbury.seng302.homehelper.repository;

import java.util.List;
import java.util.Optional;
import nz.ac.canterbury.seng302.homehelper.entity.RenovationRecord;
import nz.ac.canterbury.seng302.homehelper.entity.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RenovationRecordRepository extends JpaRepository<RenovationRecord, Long> {

    void deleteById(Long renovationId);

    Optional<RenovationRecord> findById(Long renovationId);

    @Query("SELECT r from RenovationRecord r where r.name = :name")
    RenovationRecord findRenovationByName(@Param("name") String name);

    @Query("SELECT r FROM RenovationRecord r WHERE r.user = :user")
    List<RenovationRecord> findAllByUser(@Param("user") User user);

    // Query partially generated by ChatGPT (The lower + concat parts)
    /* Will sort by id descending (i.e. newest first) if query is empty (see the CASE statement),
       then if the query has text it will sort by name first, then id descending */
    @Query("""
                SELECT r FROM RenovationRecord r
            WHERE ((:user IS NOT NULL AND (r.user = :user OR r.publicRecord = true))
                   OR (:user IS NULL AND r.publicRecord = true))
                AND (LOWER(r.name) LIKE LOWER(CONCAT('%', :query, '%'))
                    OR LOWER(r.description) LIKE LOWER(CONCAT('%', :query, '%')))
                ORDER BY
                    CASE WHEN :query = '' THEN r.id ELSE 0 END DESC,
                          r.name ASC,
                          r.id DESC
            """)
    Page<RenovationRecord> searchByNameOrDescription(
            @Param("query") String query,
            @Param("user") User user,
            Pageable pageable
    );

    @Query(value = """
            WITH searchQuery AS (
                SELECT r.id as id,
                    ROW_NUMBER() OVER (
                    ORDER BY
                        CASE WHEN :query = '' THEN r.id ELSE 0 END DESC,
                          r.name ASC,
                          r.id DESC) as index_
                FROM RenovationRecord r
                WHERE ((:user IS NOT NULL AND (r.user = :user OR r.publicRecord = true))
                       OR (:user IS NULL AND r.publicRecord = true))
                    AND (LOWER(r.name) LIKE LOWER(CONCAT('%', :query, '%'))
                        OR LOWER(r.description) LIKE LOWER(CONCAT('%', :query, '%')))
            )
            SELECT s.index_
            FROM searchQuery s
            WHERE s.id = :renovationId
            """)
    Integer findPageNumberById(@Param("renovationId") Long renovationId,
            @Param("query") String query,
            @Param("user") User user);

    List<RenovationRecord> findByUserAndNameContainingIgnoreCase(User user, String substring);

    void flush();
}
