package nz.ac.canterbury.seng302.homehelper.service;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import nz.ac.canterbury.seng302.homehelper.utils.FileUtilities;
import org.springframework.stereotype.Service;

/**
 * Service for generating random themes composed of colours, adjectives, and room types.
 * <p>
 * The service reads word lists from resources bundled in the JAR and constructs a theme with a
 * random adjective, room, and occasionally a colour. Javadoc generated by ChatGPT
 */
@Service
public class ThemeService {

    private static final String ADJECTIVES_PATH = "/adjectives.txt";
    private static final String ROOMS_PATH = "/rooms.txt";
    private static final String COLOURS_PATH = "/colours.txt";

    /**
     * Selects a random word from a list of words.
     *
     * @param words the list of words to choose from
     * @return a randomly selected word, or an empty string if the list is null or empty Javadoc
     * generated by ChatGPT
     */
    private String getRandomWord(List<String> words) {
        if (words == null || words.isEmpty()) {
            return "";
        }
        int index = ThreadLocalRandom.current().nextInt(words.size());
        String phrase = words.get(index);
        String[] parts = phrase.split(" ");
        StringBuilder result = new StringBuilder();

        // Capitalise each phrase as some are two words (e.g Living Room)
        for (String part : parts) {
            if (!part.isEmpty()) {
                result.append(part.substring(0, 1).toUpperCase())
                        .append(part.substring(1).toLowerCase())
                        .append(" ");
            }
        }

        return result.toString().trim();

    }

    /**
     * Generates a random theme string composed of an adjective and room type, optionally prefixed
     * by a colour with a 33% probability.
     *
     * @return a randomly generated theme, e.g., "green bright kitchen"
     * @throws IOException if there is an error reading any of the word resource files Javadoc
     *                     generated by ChatGPT
     */
    public String generateTheme() {
        List<String> adjectives = FileUtilities.readWordsFromResource(ADJECTIVES_PATH);
        List<String> rooms = FileUtilities.readWordsFromResource(ROOMS_PATH);
        List<String> colours = FileUtilities.readWordsFromResource(COLOURS_PATH);

        StringBuilder theme = new StringBuilder();

        // 33% chance of adding a colour
        if (ThreadLocalRandom.current().nextInt(3) == 0) {
            theme.append(getRandomWord(colours)).append(" ");
        }

        theme.append(getRandomWord(adjectives)).append(" ");
        theme.append(getRandomWord(rooms));

        return theme.toString().trim();
    }
}
