package nz.ac.canterbury.seng302.homehelper.utils;

import java.util.concurrent.ThreadLocalRandom;

/**
 * Class containing static utility methods for the reset password functionality
 */
public class ResetPasswordUtilities {

    /**
     * Method generated by ChatGPT with the prompt "use threadlocalrandom to generate a random 32
     * long string"
     * <p>
     * Generates and returns a random string of 32 characters using ThreadLocalRandom
     *
     * @return String random 32 character long token
     */
    public static String generatePasswordResetToken() {
        ThreadLocalRandom random = ThreadLocalRandom.current();
        StringBuilder sb = new StringBuilder(32);
        String validChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.";

        for (int i = 0; i < 32; i++) {
            int index = random.nextInt(validChars.length());
            sb.append(validChars.charAt(index));
        }

        return sb.toString();
    }
}
