package nz.ac.canterbury.seng302.homehelper.utils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import nz.ac.canterbury.seng302.homehelper.dto.UserDTO;
import nz.ac.canterbury.seng302.homehelper.entity.User;
import nz.ac.canterbury.seng302.homehelper.service.UserService;
import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * Static validator object to validate registration forms Resulting error messages are added to a
 * hashmap to be accessed by Thymeleaf template.
 */
public class UserDataValidator {

    // regex courtesy of https://www.baeldung.com/java-email-validation-regex modified by chatGPT
    private static final String EMAIL_REGEX = "^[\\p{L}\\p{M}\\w!#$%&'*+/=?`{|}~^+\\-]+(?:\\.[\\p{L}\\p{M}\\w!#$%&'*+/=?`{|}~^+\\-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,6}$";

    // regex courtesy of https://uibakery.io/regex-library/password
    private static final String PASSWORD_REGEX = "^(?=.*?\\p{Lu})(?=.*?\\p{Ll})(?=.*?\\p{N})(?=.*?[\\p{P}\\p{S}])[\\p{L}\\p{M}\\p{N}\\p{P}\\p{S}]{8,}$";

    // regex generated by ChatGPT
    private static final String FIRST_NAME_REGEX = "[\\p{L}\\p{M}.,' ་-]+";

    private static final String LAST_NAME_REGEX = "[\\p{L}\\p{M}.,' ་-]*";

    /**
     * Private constructor to prevent initialisation
     */
    private UserDataValidator() {
    }

    /**
     * Validates user registration form
     *
     * @param userDTO     UserDTO object holding values to be validated
     * @param userService UserService object to check whether the email is already in use
     * @return error hashmap with key of field that errored and value of error message
     */
    public static Map<String, String> validateRegistration(UserDTO userDTO,
            UserService userService) {
        HashMap<String, String> errors = new HashMap<>();
        validateEmail(errors, userDTO.getEmail(), userService, null);
        validateFirstName(errors, userDTO.getFirstName());
        validateLastName(errors, userDTO.getLastName());
        validatePassword(errors, userDTO);
        validatePasswordConfirm(errors, userDTO.getPassword(), userDTO.getPasswordConfirm());
        return errors;
    }

    /**
     * Validates user profile edit form
     *
     * @param userDTO     UserDTO object holding values to be validated
     * @param userService UserService object to check whether the email is already in use
     * @return error hashmap with key of field that errored and value of error message
     */
    public static Map<String, String> validateEditUser(UserDTO userDTO,
            UserService userService) {
        HashMap<String, String> errors = new HashMap<>();
        validateEmail(errors, userDTO.getEmail(), userService,
                userService.getLoggedUser().getEmail());
        validateFirstName(errors, userDTO.getFirstName());
        validateLastName(errors, userDTO.getLastName());
        return errors;
    }

    /**
     * Validate first name via regex and add error to hashmap
     *
     * @param errors validation errors hashmap
     * @param name   name to check
     */
    public static void validateFirstName(Map<String, String> errors, String name) {
        boolean validFirstName = name.matches(FIRST_NAME_REGEX);
        if (name == null || name.isEmpty() || name.trim().isEmpty()) {
            errors.put("firstName", "First name cannot be empty");
        } else if (name.codePointCount(0, name.length()) > 64) {
            errors.put("firstName", "First name must be 64 characters long or less");
        } else if (!validFirstName) {
            errors.put("firstName",
                    "First name must only include letters, spaces, hyphens or apostrophes");
        }
    }

    /**
     * Validate last name and add error to hashmap
     *
     * @param errors validation errors hashmap
     * @param name   name to check
     */
    public static void validateLastName(Map<String, String> errors, String name) {
        boolean validLastName = name.matches(LAST_NAME_REGEX);

        if (!validLastName && !name.isEmpty()) {
            errors.put("lastName", "Last name must only include " +
                    "letters, spaces, hyphens or apostrophes");
        } else if (name.codePointCount(0, name.length()) > 64) {
            errors.put("lastName", "Last name must be 64 characters long or less");
        }
    }

    /**
     * Validate email by regex and add error to hashmap only if the email isn't the same as the
     * current users email.
     *
     * @param errors           validation errors hashmap
     * @param email            email to check
     * @param userService      UserService object to check whether the email is already in use
     * @param currentUserEmail the current email of the logged-in user
     */
    public static void validateEmail(Map<String, String> errors, String email,
            UserService userService, String currentUserEmail) {
        email = email.toLowerCase();
        boolean validEmail = validateEmailFormat(null, email);
        List<String> emailErrors = new ArrayList<>();
        if (!email.equals(currentUserEmail) || email == null) {
            boolean emailInUse = false;
            if (email == null || email.isEmpty() || !validEmail) {
                emailErrors.add("Email address must be in the form 'jane@doe.nz'");
            } else {
                emailInUse = userService.existsByEmail(email);
            }
            if (emailInUse) {
                errors.put("emailInUse", "This email address is already in use");
            }
            if (email.codePointCount(0, email.length()) >= 256) {
                emailErrors.add("Email must be 255 characters long or less");
            }

            if (!emailErrors.isEmpty()) {
                errors.put("email", String.join(". ", emailErrors) + ".");
            }
        }

    }

    /**
     * Validates the email against the email regex. Only puts the error in the hash map if it is
     * provided.
     *
     * @param errors HashMap to add any errors into
     * @param email  String email to validate
     * @return the truth value of the string email being in email format
     */
    public static boolean validateEmailFormat(Map<String, String> errors, String email) {
        boolean validEmail = email.matches(EMAIL_REGEX);
        if (!validEmail && errors != null) {
            errors.put("email", "Email address must be in the form 'jane@doe.nz'.");
        }
        return validEmail;
    }

    /**
     * Validates the password inputs from the edit password form and adds any errors to the errors
     * Map. Checks that the old password enters matches the users current password. Checks that new
     * password is valid. Checks that the new password and confirmed password match
     *
     * @param errors          map to add any errors to
     * @param passwordEncoder the password encode
     * @param oldPassword     the user's password
     * @param newPassword     the users chosen new password
     * @param confirmPassword a confirmation of the user's new password
     * @param user            the user whose details to validate against
     */
    public static void validateEditPassword(Map<String, String> errors,
            PasswordEncoder passwordEncoder,
            String oldPassword, String newPassword, String confirmPassword, User user) {
        validateOldPasswordMatches(errors, passwordEncoder, oldPassword, user);
        validatePassword(errors, newPassword, user);
        validateNewPasswordConfirm(errors, newPassword, confirmPassword);
    }

    /**
     * Validates the password inputs from the lost password form and adds any errors to the errors
     * map. Checks that the new password is valid. Checks that the new password and confirmed
     * password match.
     *
     * @param errors          map to add any errors to
     * @param newPassword     the users chosen new password
     * @param confirmPassword a confirmation of the user's new password
     * @param user            the user whose details to validate against
     */
    public static void validateLostPassword(Map<String, String> errors, String newPassword,
            String confirmPassword, User user) {
        validatePassword(errors, newPassword, user);
        validatePasswordConfirm(errors, newPassword, confirmPassword);
    }

    /**
     * Validate the given password by checking that the password isn't weak, too long, or contains
     * any details from the user profile contained in userDTO
     *
     * @param errors  validation errors map
     * @param userDTO DTO of user entered information to validate against
     */
    public static void validatePassword(Map<String, String> errors,
            UserDTO userDTO) {
        List<String> passwordErrors = new ArrayList<>();
        validateWeakOrTooLongPassword(passwordErrors, userDTO.getPassword());
        if (!validatePasswordAgainstUserFields(userDTO)) {
            passwordErrors.add("Your password cannot contain any details from your profile");
        }

        if (!passwordErrors.isEmpty()) {
            errors.put("password", String.join(". ", passwordErrors) + ".");
        }
    }

    /**
     * Validate the given password by checking that the password isn't weak, too long, or contains
     * any details from the user
     *
     * @param errors   validation errors map
     * @param password password to validate
     * @param user     user whose fields to validate against
     */
    public static void validatePassword(Map<String, String> errors, String password,
            User user) {
        List<String> passwordErrors = new ArrayList<>();
        validateWeakOrTooLongPassword(passwordErrors, password);
        if (!validatePasswordAgainstUserFields(password, user)) {
            passwordErrors.add("Your password cannot contain any details from your profile");
        }

        if (!passwordErrors.isEmpty()) {
            errors.put("password", String.join(". ", passwordErrors) + ".");
        }
    }

    /**
     * Validate that the two given passwords match, adds an error to the Map if not
     *
     * @param errors          validation errors hashmap
     * @param password        password to check
     * @param passwordConfirm password confirmation to check
     */
    public static void validatePasswordConfirm(Map<String, String> errors,
            String password,
            String passwordConfirm) {
        boolean validPasswordConfirm = password.equals(passwordConfirm);
        if (!validPasswordConfirm) {
            errors.put("confirm", "The passwords do not match");
        }
    }

    /**
     * Validate that the two given new passwords match, adds an error to the Map if not. Different
     * error message from the above function
     *
     * @param errors          validation errors hashmap
     * @param password        password to check
     * @param passwordConfirm password confirmation to check
     */
    public static void validateNewPasswordConfirm(Map<String, String> errors,
            String password,
            String passwordConfirm) {
        boolean validPasswordConfirm = password.equals(passwordConfirm);
        if (!validPasswordConfirm) {
            errors.put("confirm", "The new passwords do not match");
        }
    }

    /**
     * Validates that the old password entered matches the password stored in the database. Adds an
     * error message to the errors Map if not.
     *
     * @param errors          Map to add error messages to
     * @param passwordEncoder PasswordEncoder to hash the password to check against.
     * @param oldPassword     old password entered by the user in the change password form
     * @param user            user to validate against
     */
    public static void validateOldPasswordMatches(Map<String, String> errors,
            PasswordEncoder passwordEncoder,
            String oldPassword, User user) {
        if (user != null) {
            String password = user.getPassword();
            if (!passwordEncoder.matches(oldPassword, password)) {
                errors.put("oldPassword", "Your old password is incorrect");
            }
        }
    }

    /**
     * Validates whether the given password is weak or too long. Adds the relevant error message for
     * any failed validation.
     *
     * @param passwordErrors {@code List<String>} to hold any password validation error messages
     * @param password       {@code String} password to validate
     */
    private static void validateWeakOrTooLongPassword(List<String> passwordErrors,
            String password) {
        boolean validPassword = password.matches(
                PASSWORD_REGEX);
        if (password == null || password.isEmpty() || !validPassword) {
            passwordErrors.add(
                    "Your password must be at least 8 characters long and include at least one uppercase letter, one lowercase letter, one number, and one special character");
        }
        if (password.codePointCount(0, password.length()) >= 256) {
            passwordErrors.add("Password must be 255 characters long or less");
        }
    }

    /**
     * Returns false if the given password contains any of the fields of the user, otherwise returns
     * true
     *
     * @param password String password to validate
     * @param user     User whose fields to check against
     * @return {@code boolean} representing whether the password doesn't contain any of the user's
     * fields i.e. whether it is valid or not
     */
    private static boolean validatePasswordAgainstUserFields(String password, User user) {
        boolean isValid = true;
        if (user != null) {
            if (!user.getFirstName().isBlank()) {
                isValid &= !password.toLowerCase().contains(user.getFirstName().toLowerCase());
            }
            if (!user.getLastName().isBlank()) {
                isValid &= !password.toLowerCase().contains(user.getLastName().toLowerCase());
            }
            if (!user.getEmail().isBlank()) {
                isValid &= !password.toLowerCase().contains(user.getEmail().toLowerCase());
            }
        }
        return isValid;
    }

    /**
     * Returns false if the given password contains any of the other fields in the userDTO,
     * otherwise returns true
     *
     * @param userDTO user to check against in DTO form
     * @return {@code boolean} representing whether the password doesn't contain any of the user's
     * fields i.e. whether it is valid or not
     */
    private static boolean validatePasswordAgainstUserFields(UserDTO userDTO) {
        boolean isValid = true;
        String password = userDTO.getPassword();
        if (!userDTO.getFirstName().isBlank()) {
            isValid &= !password.toLowerCase().contains(userDTO.getFirstName().toLowerCase());
        }
        if (!userDTO.getLastName().isBlank()) {
            isValid &= !password.toLowerCase().contains(userDTO.getLastName().toLowerCase());
        }
        if (!userDTO.getEmail().isBlank()) {
            isValid &= !password.toLowerCase().contains(userDTO.getEmail().toLowerCase());
        }
        return isValid;
    }
}
